// <auto-generated />
namespace SaleManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MigModel6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigModel6));
        
        string IMigrationMetadata.Id
        {
            get { return "201811300928131_MigModel6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
