namespace SaleManagement.Migrations
{
    using SaleManagement.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<SaleManagement.Models.DAL.ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(SaleManagement.Models.DAL.ApplicationDbContext context)
        {
            context.Admin.Add(new Models.Admin()
            {
                UserName = "minhlv",
                PasswordEncrypted = "brotherMinh",
                Salt = null,
                Status = 0,
            });

            int currentStoreID = 0;

            List<Product> products = new List<Product>();
            //products.Add(new Product() { Code="", Name="", UnitName="", RetailPrice=, WholesalePrice=, WholesaleMinAmount=, AverageCost=, DiscountRate=, Availability=, AmountSold=, CategoryName="", Origin="", BrandName="", DateCreated=DateTime.Parse(""), Image="", Description="", Status =, StoreID =currentStoreID });


            products.Add(new Product() { Code = "	SP000025	", Name = "	Mật ong nguyên chất Tây Nguyên	", UnitName = "	Hộp	", RetailPrice = 75000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 71250, DiscountRate = 0, Availability = 10, AmountSold = 0, CategoryName = "	Thực phẩm tự nhiên từ động vật	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/25.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000024	", Name = "	Mật ong rừng nguyên chất	", UnitName = "	Hộp	", RetailPrice = 250000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 237500, DiscountRate = 0, Availability = 18, AmountSold = 0, CategoryName = "	Thực phẩm tự nhiên từ động vật	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/24.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000023	", Name = "	Mật ong Breitsamer 340g	", UnitName = "	Hộp	", RetailPrice = 140000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 133000, DiscountRate = 0, Availability = 12, AmountSold = 0, CategoryName = "	Thực phẩm tự nhiên từ động vật	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/23.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000022	", Name = "	Mật ong Breitsamer 500g	", UnitName = "	Hộp	", RetailPrice = 192500, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 182875, DiscountRate = 0, Availability = 10, AmountSold = 0, CategoryName = "	Thực phẩm tự nhiên từ động vật	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/22.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000021	", Name = "	Mật ong Breitsamer 250g	", UnitName = "	Hộp	", RetailPrice = 105000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 99750, DiscountRate = 0, Availability = 4, AmountSold = 0, CategoryName = "	Thực phẩm tự nhiên từ động vật	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/21.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000020	", Name = "	Yến mạch nguyên chất ăn liền	", UnitName = "	Hộp	", RetailPrice = 102000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 96900, DiscountRate = 0, Availability = 0, AmountSold = 0, CategoryName = "	Ngũ cốc, sản phẩm từ ngũ cốc	", Origin = "	Việt Nam	", BrandName = "	Quế Lân INC	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/20.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000019	", Name = "	Yến mạch nguyên chất Captain Oats	", UnitName = "	Hộp	", RetailPrice = 75000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 71250, DiscountRate = 0, Availability = 4, AmountSold = 0, CategoryName = "	Ngũ cốc, sản phẩm từ ngũ cốc	", Origin = "	Việt Nam	", BrandName = "	Quế Lân INC	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/19.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000018	", Name = "	Yến mạch Captain Oát - Instant Oatmeal 500g	", UnitName = "	Hộp	", RetailPrice = 80000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 76000, DiscountRate = 0, Availability = 4, AmountSold = 0, CategoryName = "	Ngũ cốc, sản phẩm từ ngũ cốc	", Origin = "	Việt Nam	", BrandName = "	Quế Lân INC	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/18.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000017	", Name = "	Ngũ cốc dinh dưỡng canxi	", UnitName = "	Hộp	", RetailPrice = 47000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 44650, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Ngũ cốc, sản phẩm từ ngũ cốc	", Origin = "	Việt Nam	", BrandName = "	Quế Lân INC	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/17.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000016	", Name = "	Yến mạch Captain Oats - Quick Cook 1kg	", UnitName = "	Hộp	", RetailPrice = 150000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 142500, DiscountRate = 0, Availability = 4, AmountSold = 0, CategoryName = "	Ngũ cốc, sản phẩm từ ngũ cốc	", Origin = "	Việt Nam	", BrandName = "	Quế Lân INC	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/16.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000015	", Name = "	Mắt cá Ngừ đại dương	", UnitName = "	Hộp	", RetailPrice = 16000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 15200, DiscountRate = 0, Availability = 6, AmountSold = 0, CategoryName = "	Đặc sản	", Origin = "	Việt Nam	", BrandName = "	Thanh Bình Corp	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/15.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000014	", Name = "	Tré Bình Định	", UnitName = "	Hộp	", RetailPrice = 45000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 42750, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Đặc sản	", Origin = "	Việt Nam	", BrandName = "	Thanh Bình Corp	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/14.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000013	", Name = "	Tỏi Lý Sơn 500gr	", UnitName = "	Hộp	", RetailPrice = 65000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 61750, DiscountRate = 0, Availability = 12, AmountSold = 0, CategoryName = "	Đặc sản	", Origin = "	Việt Nam	", BrandName = "	Thanh Bình Corp	", DateCreated = DateTime.Parse("	43223	"), Image = "	/Content/product_images/food/13.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000012	", Name = "	Mật ong rừng U Minh 500ml	", UnitName = "	Hộp	", RetailPrice = 190000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 180500, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Đặc sản	", Origin = "	Việt Nam	", BrandName = "	Thanh Bình Corp	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/12.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000011	", Name = "	Miến Dong	", UnitName = "	Hộp	", RetailPrice = 63000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 59850, DiscountRate = 0, Availability = 12, AmountSold = 0, CategoryName = "	Đặc sản	", Origin = "	Việt Nam	", BrandName = "	Thanh Bình Corp	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/11.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000010	", Name = "	Đậu phộng rang Tuệ Giác	", UnitName = "	Hộp	", RetailPrice = 60000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 57000, DiscountRate = 0, Availability = 6, AmountSold = 0, CategoryName = "	Thực phẩm chín, qua chế biến	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/10.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000009	", Name = "	Mực một nắng Thanh Ký	", UnitName = "	Hộp	", RetailPrice = 280000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 266000, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Thực phẩm chín, qua chế biến	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/9.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000008	", Name = "	Heo một nắng Thanh Ký	", UnitName = "	Hộp	", RetailPrice = 139000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 132050, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Thực phẩm chín, qua chế biến	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/8.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000007	", Name = "	Yến Thiên sơ chế 100gr	", UnitName = "	Hộp	", RetailPrice = 2800000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 2660000, DiscountRate = 0, Availability = 2, AmountSold = 0, CategoryName = "	Thực phẩm chín, qua chế biến	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/7.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000006	", Name = "	Chả bò Đà Nẵng	", UnitName = "	Hộp	", RetailPrice = 154000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 146300, DiscountRate = 0, Availability = 2, AmountSold = 0, CategoryName = "	Thực phẩm chín, qua chế biến	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/6.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000005	", Name = "	Cá thu một nắng bịch 500gr	", UnitName = "	Hộp	", RetailPrice = 195000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 185250, DiscountRate = 0, Availability = 8, AmountSold = 0, CategoryName = "	Thực phẩm tươi sống	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/5.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000004	", Name = "	Nấm mối làm sẵn bịch 500gr	", UnitName = "	Hộp	", RetailPrice = 145000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 137750, DiscountRate = 0, Availability = 10, AmountSold = 0, CategoryName = "	Thực phẩm tươi sống	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/4.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000003	", Name = "	Tôm sú tươi sống	", UnitName = "	Hộp	", RetailPrice = 200000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 190000, DiscountRate = 0, Availability = 6, AmountSold = 0, CategoryName = "	Thực phẩm tươi sống	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/3.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000002	", Name = "	Phi lê cá Ngừ đại dương	", UnitName = "	Hộp	", RetailPrice = 230000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 218500, DiscountRate = 0, Availability = 4, AmountSold = 0, CategoryName = "	Thực phẩm tươi sống	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/2.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });
            products.Add(new Product() { Code = "	SP000001	", Name = "	Cá mặt quỷ	", UnitName = "	Hộp	", RetailPrice = 650000, WholesalePrice = 100000, WholesaleMinAmount = 9999999, AverageCost = 617500, DiscountRate = 0, Availability = 10, AmountSold = 0, CategoryName = "	Thực phẩm tươi sống	", Origin = "	Việt Nam	", BrandName = "	Thảo Thảo Pharm	", DateCreated = DateTime.Parse("	43415	"), Image = "	/Content/product_images/food/1.jpg	", Description = "	Nội dung mô tả …	", Status = 0, StoreID = currentStoreID });



        }
    }
}
